name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Replace PROMOCODES placeholder
        env:
          PROMOCODES_ANDROID: ${{ vars.PROMOCODES_ANDROID }}
        run: |
          # Convert promocodes to array
          IFS=$'\n' read -d '' -r -a promocodes <<< "$PROMOCODES_ANDROID"
      
          # Generate links
          links=""
          for code in "${promocodes[@]}"; do
          links+="<p><a href=\"https://play.google.com/redeem?code=${code}\">${code}</a></p>"$'\n'
          done
      
          # Escape special characters for sed
          escaped_links=$(printf '%s\n' "$links" | sed -e 's/[\/&]/\\&/g')
      
          # Replace placeholder in file
          sed -i "s|-PROMOCODES-|${escaped_links}|g" promocodes.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
