name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Replace PROMOCODES placeholder
        env:
          PROMOCODES_ANDROID: ${{ vars.PROMOCODES_ANDROID }}
        run: |
          mkdir -p public
          
          # Generate links
          links=""
          while IFS= read -r code || [[ -n "$code" ]]; do
          if [[ -n "$code" ]]; then
          links+="<p><a href=\"https://play.google.com/redeem?code=${code}\">${code}</a></p></br>"$'\n'
          fi
          done <<< "$PROMOCODES_ANDROID"
      
          # Replace placeholder in file using awk
          awk -v r="$links" '{gsub(/-PROMOCODES-/,r)}1' promocodes.html > public/promocodes.html
          # Print the result for debugging (optional)
          echo "Resulting public/promocodes.html:"
          cat public/promocodes.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
