name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Replace PROMOCODES placeholder
        env:
          PROMOCODES_ANDROID: ${{ vars.PROMOCODES_ANDROID }}
        run: |
          # Generate links
          links=""
          while IFS= read -r code || [[ -n "$code" ]]; do
          if [[ -n "$code" ]]; then
          links+="<p><a href=\"https://play.google.com/redeem?code=${code}\">${code}</a></p>"$'\n'
          fi
          done <<< "$PROMOCODES_ANDROID"
      
          # Escape special characters for sed
          escaped_links=$(printf '%s\n' "$links" | sed -e 's/[\/&]/\\&/g')
      
          # Replace placeholder in file
          sed -i "s|-PROMOCODES-|${escaped_links}|g" promocodes.html
      
          # Print the result for debugging (optional)
          echo "Resulting HTML:"
          cat promocodes.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
